IMAGE_NAME = "bento/debian-12"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
        debian.vm.network "forwarded_port", guest: 22, host: 2207, host_ip: "127.0.0.1"
        debian.vm.network "forwarded_port", guest: 80, host: 8808, host_ip: "127.0.0.1"
        debian.vm.hostname = "baudysm"
    end
	
config.vm.provision "shell", path: "provision.sh"
end
